### ISSUE TITLE
Fatal error: Class 'okw\CF\Exception\CFException' not found

### ISSUE THREAD

**Issue by OwenMelbz** [okwinza/CloudFlare-API#5]
Hi All, 

I'm using Laravel 5.2 and have a controller thats firing an exception, however the class is then erroring internally, not sure what I'm doing wrong?

``` php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use \okw\CF\CF;

class CloudflareController extends Controller
{
    public function purge_url(Request $request, $url)
    {
        $api_client = new CF( 'email.com', 'key.com' );

            $response = $api_client->zone_file_purge([
                  'z' => 'domain.com',
                  'url' => 'domain.com/file'
            ]);
    }
}
```

I understand WHY its throwing the exception thats fine, however i get a different error

``` json
{
message: "Fatal error: Class 'okw\CF\Exception\CFException' not found",
status_code: 500,
debug: {
line: 167,
file: "/home/vagrant/selesti-api/vendor/okwinza/cloudflare-api/okw/CF/CF.php",
class: "Symfony\Component\Debug\Exception\FatalThrowableError",
trace: [
"#0 /home/vagrant/selesti-api/vendor/okwinza/cloudflare-api/okw/CF/CF.php(67): okw\CF\CF->executeRequest(Array)",
"#1 /home/vagrant/selesti-api/vendor/okwinza/cloudflare-api/okw/CF/CF.php(56): okw\CF\CF->post('zone_file_purge', Array)",
"#2 /home/vagrant/selesti-api/app/Http/Controllers/CloudflareController.php(43): okw\CF\CF->__call('zone_file_purge', Array)"]
}
```

**Comment by okwinza** [comment]
Hey @OwenMelbz! Thanks for reporting this.

Looks like something is wrong with your compiled class map.
Try run `php artisan optimize`.

Might be related: https://github.com/laravel/framework/issues/2553

**Comment by okwinza** [comment]
Gonna close this for now, please reopen if issue is not solved.
